version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/products-ms
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${ORDERS_DB_URL}
    ports:
      - "3002:3002"
    image: southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/orders-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_DB_URL}
      - NATS_SERVERS=nats://nats-server:4222

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - "3003:3003"
    image: southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/payments-ms
    environment:
      - PORT=3003
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${PAYMENTS_STRIPE_WEBHOOK_SECRET}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    ports:
      - "3004:3004"
    image: southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
